# Generated by Django 4.1.13 on 2023-12-04 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option4',
        ),
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
