# Generated by Django 4.1.13 on 2023-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_remove_quiz_option1_remove_quiz_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
